name: EasyDisplayEditor
version: '${project.version}'
main: com.kamesuta.easydisplayeditor.EasyDisplayEditor
api-version: "1.20"
authors: [ Kamesuta ]
softdepend:
  - ProtocolLib

commands:
  ede:
    description: EasyDisplayEditor
    usage: /ede <give> [args]
    permission: ede.command

permissions:
  ede.command:
    description: Allows access to EasyDisplayEditor command
    default: true
